# Application of Numpy

Mathematics (MATLAB Replacement)
<br>Plotting </br> 
<br>Machine Learning</br>


In [2]:
import numpy as np


## The Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension array 
print(b.ndim) # this is 2 dimensional array
print(a.ndim) # this is 1 dimensional array

2
1


In [5]:
# Get Shape gives us vector
print(a.shape) # 3 columns, 1 row vector
print(b.shape) # 2 rows, 3 columns vector


(3,)
(2, 3)


In [6]:
# Get Type
a.dtype

dtype('int64')

## Accessing/Changing specific elements, rows, columns, etc


In [7]:
a = np.array([[1,2,3,4,5,6,7], [2,3,4,5667,123,6,3]])
print(a)
print(a.shape) # this will be 2 by 7 vector

[[   1    2    3    4    5    6    7]
 [   2    3    4 5667  123    6    3]]
(2, 7)


In [8]:
# Get a specific element [r, c]
# suppose we want to get 5667 in our matrix

a[1, 3] #notice that index starts at 0

5667

In [9]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
# Get a specific columns
a[:, 3]

array([   4, 5667])

In [11]:
# Getting a little more fancy [startindex:endindex:skipstep]
a[0, 1:6:2] # not including 6

array([2, 4, 6])

In [12]:
a[0,:] = 20
print(a)

a[0, :] = 5
print(a)

[[  20   20   20   20   20   20   20]
 [   2    3    4 5667  123    6    3]]
[[   5    5    5    5    5    5    5]
 [   2    3    4 5667  123    6    3]]


*3-d example

In [13]:
b = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
# Get specific element (work outside in)
b[0,1,1] # this will give us 4

4

In [15]:
# replace 
b[:, 1, :] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different Types of Arrays

In [16]:
# All 0s matrix
np.zeros((2,3)) # 2 by 3 matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# All 1s matrix
np.ones((4,2,2)) # 4 by 2 by 2 matrix

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [18]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [19]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [20]:
# Random decimal numbers
np.random.rand(4,2) # random values for 4 by 2 matrix

array([[0.11110648, 0.75002225],
       [0.16261707, 0.06140326],
       [0.99836817, 0.76586969],
       [0.48002068, 0.37844665]])

In [21]:
# Random integer values
np.random.randint(4, 7, size=(3,3)) # size is 3 by 3 matrix

array([[4, 6, 4],
       [5, 6, 4],
       [5, 6, 6]])

In [22]:
np.identity(3) # identity matrix of 3 by 3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
#problem 1 
a = np.ones((5,5))
a[1, 1:4] = 0
a[1:4, 1] = 0
a[-2, 1:4] = 0
a[1:4, -2] = 0
a[2,2] = 9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


*Be careful when copying arrays!!!

In [22]:
a = np.array([1,2,3])
b = a.copy() # using this method, we don't have the same reference
b[0] = 100

print(a)
print(b) 

[1 2 3]
[100   2   3]


# Mathematics

In [24]:
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [25]:
a + 2

array([3, 4, 5, 6])

In [26]:
a - 2

array([-1,  0,  1,  2])

In [27]:
a * 2


array([2, 4, 6, 8])

In [28]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [30]:
#adding two matrix
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [31]:
a ** 2

array([ 1,  4,  9, 16])

In [32]:
# take the sin of all values
np.sin(a) # notice a is a matrix

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [38]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)



np.matmul(a,b) #multiply 2 matrix

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [39]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics


In [40]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
np.min(stats)

1

In [42]:
np.max(stats)

6

In [43]:
np.sum(stats)

21

#### Reorganizing Arrays

In [46]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((8,1)) # now we reshape into a 8 by 1 matrix
print(after) 

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


*Note you will get error if there is mismatch in reshaping

In [47]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2]) # combine matrices and stack them vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [3]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])